export const UserErrors = {
   UserIdRequired: "user_id is required",
   EmailAddressRequired: "email address is required",
   EmailAddressInvalid: "Not a proper email address",
   PasswordRequired: "password is required",
   UserNotFound: 'User not found',
   VerificationTokenRequired: 'Verification token is required',
   InvalidVerificationToken: "No user found with that verification token",
   UserVerified: "This user has already been verified successfully",
   ResetTokenRequired: 'reset_token is required',
   UserExist: 'User account already exist',
   UserNotAllowed: "You do not have the rights to update this user account",
   PasswordsMismatch: "The passwords entered do not match",
   RefreshTokenRequired: 'refresh_token is required',
   FirstNameRequired: 'first_name is required',
   LastNameRequired: 'last_name is required',
   GenderRequired: 'gender is required',
   DOBRequired: 'dob is required',
   AgeMinimumRequirement: "You must be at least 15 years old.",
   GenderNotListed: "Not currently a valid gender",
   CountryRequired: "country is required",
   InvalidCountry: "Not a valid country at the moment",
   FirstNameMinRequirement: "First name must have at least 2 characters",
   LastNameMinRequirement: "Last name must have at least 2 characters",
   PasswordComplexityRequirement: "Password must be at least 8 characters long"
}